server:
  port: 8888
  servlet:
    context-path: /config

spring:
  main:
    banner-mode: off
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/UJ-Masters/config-service
          default-label: main
  boot:
    admin:
      client:
        url: http://localhost:7777/admin

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
